### ISSUE TITLE
Do we really need separate DAO interfaces?

### ISSUE THREAD

**Issue by kahowell** [esbtools/esb-message-admin#118]
Seems to me it'd simplify the code to collapse `AuditEventDao` and `AuditEventDaoImpl` into simply `AuditEventDao` and do similarly for all other DAO classes... Thoughts?

**Comment by alechenninger** [comment]
These would be useful if the `EsbMessageAdminServiceImpl` injected its DAO members. Then, this class could be unit tested in isolation from specific DAO implementation (which would be separately tested).

**Comment by kahowell** [comment]
Couldn't you still just mock out the DAO classes anyways, even without the interfaces?

**Comment by alechenninger** [comment]
Yep you are right of course. Personally I just prefer to have interfaces. Keeps things a little cleaner, and decision making easier (No need to even ask, "should I have an interface for this?": yes and move on IMHO unless it would fit as a final class). It _is_ unfortunately verbose however... but there is a certain semantic meaning of the interfaces which I think is why you tend to see this kind of thing (gratuitous interface "padding") even though there is often only one implementation. I see it as an unfortunate but necessary artifact of Java*. Worst case? You have an extra interface worth of code (~20-50 lines if that). Best case, you need the interface and don't have to refactor one out. Easy future proofing at little cost IMHO. Say you want to try implementing a DAO using Lightblue... *shrug*

Just my 2c... if you and Derek would rather collapse them I won't say another word :). This kind of thing may come up again, however.

* For instance, in Go, or Javascript, there is no need for this as they are both "duck-typed." Or in Dart, every class is also an implicit interface, etc... I blame Java! :)

**Comment by derek63** [comment]
I could go either way on having the interface...I like having them for wiring up stuff differently per purpose (unit tests, integration test, deployment, etc.) without having to mock, but don't like dealing with them when I am developing (and hate putting an Impl suffix on the end of otherwise well-named objects).  

What I am not sure about is if we need a DAO layer at all in this app?  A lot of what is in there at the moment is massaging of the data out of model and into *entity classes, doing formatting/massaging of data, and maybe a line or two of code in each DAO method actually doing data access.  And a lot of what is in the service layer is one line that calls a method on the DAO layer.  At a minimum we could collapse those two layers into one, since JPA is providing the needed datasource abstraction at this time, and nothing we are doing in EMA has complicated business rules or interactions between objects.  And because we considered using lightblue at the beginning of this project, and ruled it out, so I know we won't be writing a lightblue adapter any time soon :-)

Maybe I have just been drinking the Spring Data kool-aid, but it kinda feels like the layers are just here for the sake of having layers

**Comment by alechenninger** [comment]
Good points, and +1 to reducing the amount of layers since it sounds like there isn't any gain from having so many.
